### ISSUE TITLE
Use existing UDisks library

### ISSUE THREAD

**Issue by donadigo** [elementary/pantheon-installer#20]
Instead of having connect to DBus interfaces, use existing UDisks library, it has vapi for it, and is documented on valadoc:
http://www.valadate.org:8000/#!api=udisks2/UDisks
(the link won't work, but a simple search for udisks will do).

**Comment by tintou** [comment]
UDisks might be replaced by Storaged in the future, and they target DBus compatibility so I prefer to use the DBus interface directly. In top of that, the API is just a wrapper for the DBus interface so it's not worth using it in Vala

**Comment by danrabbit** [comment]
Closing this due to comments
