### ISSUE TITLE
Many failed downloads of Elementary OS

### ISSUE THREAD

**Issue by gusbemacbe** [elementary/pantheon-installer#34]
Hello, when I tried to update the system or upgrade the archives to update the system, but it gave many failed downloads and some were forbidden because of security. Please check my file attached.

[failed-downloads.txt](https://github.com/elementary/pantheon-installer/files/839902/failed-downloads.txt)

**Comment by danrabbit** [comment]
Pantheon Installer isn't currently deployed, so it's not possible that it could have an effect on your system. Closing this issue because it is invalid for this project
