### ISSUE TITLE
Consider Using Calamares

### ISSUE THREAD

**Issue by djhetherington** [elementary/pantheon-installer#36]
I stumbled across Calamares, a installer framework, I had a look at the code, and it seems to me elementary OS could be integrated into the code to make a installer.

I tried to look at the ubiquity code to see what could be put into the Calamares modules but ubiquity is a mess :L 

https://github.com/calamares/calamares

**Comment by tintou** [comment]
Sounds unlikely, Calamares is made in Qt, using Python and libboost when we are using GLib + Gtk+ everywhere

**Comment by tintou** [comment]
Anaconda (but #30) is a better option for us
