### ISSUE TITLE
Start with a simple welcome page

### ISSUE THREAD

**Issue by vjr** [elementary/pantheon-installer#38]
The first screen is currently the language selection. It might be nice to have a welcome page first with a simple blue elementary logo, the text "elementary OS", a short welcome text and a single "Begin Installation" button.

Might I suggest the short welcome text be the following line from your website?

"A fast and open replacement for Windows and macOS"

Even though the user might previously select from a boot menu options like "try elementary OS" and "install elementary OS" (she has alread indicated to start the installer) - it would still be nice to have this start page.

**Comment by tintou** [comment]
Why do you want to show text when the user hasn't selected his language ;)
He wouldn't be able to read it

**Comment by vjr** [comment]
Doh. Yeah! :-)  Note the current start page shows "Select a Language" at the top of (above) the language list in English... or is that because its already a translated string and my language is already set to english?

**Comment by vjr** [comment]
Maybe just show the elementary icon and that thing where there is a "word cloud" of the word "Welcome" in multiple languages scattered across the area with the most popular ones being larger and in the middle?

**Comment by tintou** [comment]
There is a timer that translated the sentence "Select a Language" to every language of the list, it's just that we have no translation right now :stuck_out_tongue:

**Comment by vjr** [comment]
No way! That's cool.

**Comment by danrabbit** [comment]
Eh gonna mark this as a "won't fix". I think the metric for success of an installer is "least possible amount of time interacting with this"
