### ISSUE TITLE
Installer should not change the hostname of an existing linux system on the machine

### ISSUE THREAD

**Issue by DamageIncorporated** [elementary/pantheon-installer#43]
**What happened:**
I am planning to install elementary (for my wife) on a separate partition alongside my existing Arch/Antergos install.

I booted from the usb-key, selected "Install" and aborted the installer after selecting the "download updates during install" stage. (Forgot to backup something :-) )

After rebooting to antergos I found that the installer had changed the hostname _on the arch root partition_ to "elementary". 

**Expected behaviour:**
The installer should never touch the root partition of an existing linux (or other os) on the machine if I did not choose to delete it completely (exception: update grub).

The installer should not touch anything on the harddisk drive until all settings are made and I answer the last "are you sure?" question.

**Question:**
 Can I install elementary on a seperate partition at all or do I have to expect it messes up my existing install?

**Comment by vjr** [comment]
> Can I install elementary on a seperate partition at all or do I have to expect it messes up my existing install?

If it helps any, the installer works fine for me with a multi boot of Windows10, Fedora, Ubuntu, KDE Neon, other elementary partitions (yes, that many!) on my GPT partitioned disk with my UEFI (secure boot disabled) desktop.

**Comment by vjr** [comment]
Also, IINM this is the repo for the new experimental (work in progress) "pantheon" installer and not the ubuntu-based "ubiquity" installer. It might actually be an upstream issue with the ubuntu ubiquity installer, but I could be wrong.

**Comment by DamageIncorporated** [comment]
hey @vjr,

thanx for your quick comment! That eases my concerns :-)

For ubiquity/pantheon issue. I'll look for the other installer and file this bug again, referencing this one here to be safe :-)

**Comment by Conan-Kudo** [comment]
@DamageIncorporated Pantheon Installer is not used in Elementary OS. This is a Ubiquity issue.

**Comment by DamageIncorporated** [comment]
Okay :-)

Seems I did not find the proper spot to file this issue..

I reported in a ubiquity tracker as advised (the only one I could find), where the issue got invalidated too. Comment was "I can not speak for another OS, but ubiquity in Ubuntu certainly does
not touch other OS's partitions."

So be it ... 
I think I'll swap out my ssd and use a blank one for now ... safety first ;-)
